version: "3"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: always
    ports:
      - "8008:8008"   # HTTP (client-server 통신)
      - "8448:8448"   # HTTPS (federation, 외부 매트릭스 서버와 통신 시)
    volumes:
      - ./data:/data  # 데이터(설정/DB) 영구 저장
    environment:
      - SYNAPSE_SERVER_NAME=matrix.localhost
      - SYNAPSE_REPORT_STATS=no
      # 필요하다면 아래처럼 관리 비밀번호나 Registration 관련 환경변수를 추가할 수도 있음
