version: "3.8"
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    volumes:
      - ./data/synapse-data:/data
      - ./config:/config
    ports:
      - "8008:8008"
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - synapse
      - slack-bridge

  slack-bridge:
    image: matrix-org/matrix-appservice-slack:latest
    container_name: slack-bridge
    volumes:
      - ./data/slack-bridge-data:/data
      - ./config/slack-registration.yaml:/data/registration.yaml
    ports:
      - "29328:29328"
    depends_on:
      - synapse
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_EVENT_URL=${SLACK_EVENT_URL}
      - MATRIX_HOMESERVER_URL=http://synapse:8008
      - MATRIX_DOMAIN=${SYNAPSE_SERVER_NAME}
    env_file:
      - .env